version: '3'
services:
  bot:
    build:
      context: .
      args:
        TOKEN: TOKEN
    depends_on:
      - safecoin
    restart: unless-stopped
  safecoin:
    image: safecoin/safecoin
    command: -rpcauth=user:password rpcallowip=0.0.0.0/0
    volumes:
      - safecoin-data:/safecoin
    restart: unless-stopped
    stop_grace_period: 2m

volumes:
  safecoin-data: